Vlv2TbltDevicePkg/PlatformPei: Remove the unused variable
Fix the following error from gcc:

Vlv2TbltDevicePkg/PlatformPei/MemoryCallback.c: In function ‘MemoryDiscoveredPpiNotifyCallback’:
Vlv2TbltDevicePkg/PlatformPei/MemoryCallback.c:115:20: error: variable ‘Status’ set but not used [-Werror=unused-but-set-variable]

Cc: David Wei <david.wei@intel.com>
Cc: Tim He <tim.he@intel.com>
Contributed-under: TianoCore Contribution Agreement 1.0
Signed-off-by: Gary Lin <glin@suse.com>